### ISSUE TITLE
Cookie policy notification

### ISSUE THREAD

**Issue by rskikuli** [Identihub/identihub.co#2]
We need to disclose our cookie policy on the website based on EU law https://www.cookielaw.org/the-cookie-law/.
The way it appears here might help https://qwtel.com/hydejack/ (see how it is displayed on top of the page) - code https://github.com/qwtel/hydejack.
Deadline: 1.03.2017.

**Comment by AnXh3L0** [comment]
Cookie policy has been implemented in the website based on the EU laws. The cookie data is retained for a period of 365 days (can be changed if necessary). Closing issue!
